name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # build at least once a month
    - cron: '0 0 1 * *'

jobs:
  build:
    strategy:
      matrix:
        include:
          - ARCH: x86_64
            DOCKER_IMAGE: quay.io/appimage/appimagebuild
          - ARCH: i686
            DOCKER_IMAGE: quay.io/appimage/appimagebuild-i386
      fail-fast: false

    name: ${{ matrix.BUILD_TYPE }} ${{ matrix.ARCH }}
    runs-on: ubuntu-latest

    env:
      ARCH: ${{ matrix.ARCH }}
      DOCKER_IMAGE: ${{ matrix.DOCKER_IMAGE }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: docker run --rm -it -e ARCH -v "$PWD":/ws -w /ws "$DOCKER_IMAGE" /bin/bash -xe ./generate-plugin-script.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: plugin script
          path: linuxdeploy-plugin-checkrt-"$ARCH".sh

  upload:
    name: Create release and upload artifacts
    needs:
      - build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage **/linuxdeploy*.AppImage*
